name: Docs to HTML

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'teoria/**.md'
      - 'teoria/images/**'

jobs:
  converttohtml:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Flatten image directory by copying
        run: |
            find teoria/images -type f -name "*.png" -exec cp {} teoria/images/ \;
            find teoria/images -type f -name "*.jpg" -exec cp {} teoria/images/ \;
            find teoria/images -type f -name "*.jpeg" -exec cp {} teoria/images/ \;
            find teoria/images -type f -name "*.gif" -exec cp {} teoria/images/ \;
            find teoria/images -type f -name "*.svg" -exec cp {} teoria/images/ \;
            ls -la teoria/images

      - name: Preprocess Obsidian Markdown
        run: |
          find teoria -type f -name "*.md" -exec sed -i 's/!\[\[\(.*\)\]\]/![\1](images\/\1)/g' {} +
          find teoria -type f -name "*.md" -exec sed -i '/table-of-contents/{N;d;}' {} +

        # https://github.com/BaileyJM02/markdown-to-pdf
      - name: Convert Markdown to HTML
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: teoria
          output_dir: tmp/
          images_dir: teoria/images/**
          build_pdf: false
          build_html: true
          table_of_contents: true

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Refactor artifacts
        run: |
          ls -la
          ls -la tmp
          mkdir -p artifacts/html
          cp tmp/*.html artifacts/html/ || echo "No HTML files to copy"
          ls -la artifacts/html

      - name: Copy images for HTML files
        run: |
          mkdir -p artifacts/html/images/
          cp teoria/images/*.png artifacts/html/images/     || echo "No png files to copy"
          cp teoria/images/*.jpg artifacts/html/images/     || echo "No jpg files to copy"
          cp teoria/images/*.jpeg artifacts/html/images/    || echo "No jpeg files to copy"
          cp teoria/images/*.gif artifacts/html/images/     || echo "No gif files to copy"
          cp teoria/images/*.svg artifacts/html/images/     || echo "No svg files to copy"
          ls -la artifacts/html/images/

      - name: Inject MathJax for LaTeX rendering
        run: |
          for html_file in artifacts/html/*.html; do
            sed -i '/<\/head>/i <script> MathJax = { tex: { inlineMath: [["$", "$"]] } }; </script>' $html_file
            sed -i '/<\/head>/i <script type="text/javascript" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>' $html_file
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs-html
          path: artifacts

      - name: Commit and Push artifacts
        run: |
          git pull
          git add artifacts/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add generated artifacts [HTML]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
